#4372 WIP: Using sat to migrate twice in a row leads to an error
RHEAGROUP/COMET-Server-Administration-Tool pull request #103
Opened 2021-04-26 13:24 UTC by adrianchivu

### Prerequisites

- [X] I have written a descriptive pull-request title
- [X] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-Server-Administration-Tool/pulls) open
- [X] I have verified that I am following the CDP4-SDK [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-Server-Administration-Tool/master/.github/CONTRIBUTING.md)
- [ ] I have provided test coverage for my change (where applicable)

### Description

2021-04-29 09:47 UTC, cozminvelciu reviewed
The diff is also showing the changes from #102. We probably need to update the branch.

2021-04-29 09:47 UTC, cozminvelciu commented on Modules/Common/Events/LogoutAndLoginEvent.cs
> +}
Missing newline at end of file.

2021-04-29 09:47 UTC, cozminvelciu commented on Modules/Migration.Tests/LoginViewModelTestFixture.cs
>  }
Missing newline at end of file.

2021-04-29 09:51 UTC, cozminvelciu requested changes

2021-04-29 09:51 UTC, cozminvelciu commented on Modules/Common/ViewModels/LoginViewModel.cs
> +        /// <param name="currentSession"></param>
Missing XML docs.

2021-04-29 09:51 UTC, cozminvelciu commented on Modules/Migration/Utils/Migration.cs
> +                CDPMessageBus.Current.SendMessage(new LogoutAndLoginEvent {CurrentSession = this.TargetSession});
Add whitespace after opening brace and before closing brace,

2021-04-29 09:51 UTC, cozminvelciu commented on Modules/Migration/Utils/Migration.cs
> +                CDPMessageBus.Current.SendMessage(new LogoutAndLoginEvent {CurrentSession = this.SourceSession});
Add whitespace after opening brace and before closing brace,

2021-04-29 09:51 UTC, cozminvelciu commented on Modules/Migration/ViewModels/MigrationViewModel.cs
> +
Unneeded extra newline.

2021-05-04 10:25 UTC, cozminvelciu requested changes

2021-05-04 10:25 UTC, cozminvelciu commented on Modules/Common/ViewModels/LoginViewModel.cs
> +        /// <param name="currentSession">Current user session<see cref="ISession"/></param>
Missing whitespace. Would suggest:
```
/// <param name="currentSession">Current user <see cref="ISession"/></param>
```

2021-05-04 10:25 UTC, cozminvelciu commented on Modules/Migration.Tests/LoginViewModelTestFixture.cs
> +using CDP4Dal;
Usings inside namespace.

2021-05-06 08:54 UTC, alexatrhea approved these changes

2021-05-06 11:01 UTC, cozminvelciu approved these changes

2021-05-07 08:17 UTC, merged