WIP: #117 stress generator additional options changes
RHEAGROUP/COMET-Server-Administration-Tool pull request #126
Opened 2021-06-25 13:36 UTC by adrianchivu

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-Server-Administration-Tool/pulls) open
- [x] I have verified that I am following the CDP4-Server-Administration-Tool [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-Server-Administration-Tool/master/.github/CONTRIBUTING.md)
- [ ] I have provided test coverage for my change (where applicable)

### Description

2021-06-28 15:55 UTC, cozminvelciu requested changes
This needs to integrate the changes from #123 (MR #124) regarding write with retries.

2021-06-28 15:55 UTC, cozminvelciu commented on Modules/StressGenerator/Views/Layout.xaml
> +                    For safety, the short name of the engineering model must start with 'StressTester_TemporaryTestModel'.
I would align this with the command_line_tools requirement:
```
if (!this.options.Model.StartsWith("StressGenerator"))
{
    Logger.Fatal("Invalid short name in --model: {0}. For safety, the short name of the engineering model must start with \"StressGenerator\".", this.options.Model);
    Environment.Exit(1);
}
```

2021-06-28 15:55 UTC, cozminvelciu commented on Modules/StressGenerator/Views/Layout.xaml
> +                    For safety, the short name of the engineering model must start with 'StressTester_TemporaryTestModel'.
Also, is there any way to get the model prefix from the `***Configration.cs` file rather than hardcode it here?

2021-06-28 15:55 UTC, cozminvelciu commented on Modules/StressGenerator/ViewModels/StressGeneratorConfiguration.cs
> +        public const string ModelPrefix = "StressTester_TemporaryTestModel";
I would align this with the command_line_tools requirement:
```
if (!this.options.Model.StartsWith("StressGenerator"))
{
    Logger.Fatal("Invalid short name in --model: {0}. For safety, the short name of the engineering model must start with \"StressGenerator\".", this.options.Model);
    Environment.Exit(1);
}
```

2021-06-28 15:55 UTC, cozminvelciu commented on Modules/StressGenerator/ViewModels/StressGeneratorConfiguration.cs
> +                    this.testObjectsNumber = MinNumberOfTestObjects;
Will the user get any feedback if the entered configuration value is silently overridden by this setter?

2021-06-28 15:55 UTC, cozminvelciu commented on Modules/StressGenerator/ViewModels/StressGeneratorConfiguration.cs
> +            this.TestObjectsNumber = 5;
I believe we don't need this here any more, as it is already initialized to `MinNumberOfTestObjects`.

2021-06-28 15:55 UTC, cozminvelciu commented on Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
> +        private ObservableAsPropertyHelper<bool> canStress;
Why can this no longer be readonly?

2021-06-28 15:55 UTC, cozminvelciu commented on Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
> +        public bool ModeCreate
Missing XML docs.

2021-06-28 15:55 UTC, cozminvelciu commented on Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
> +        public bool ModeOpenOrOverwrite
Missing XML docs.

2021-06-28 15:55 UTC, cozminvelciu commented on Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
> +        public bool SourceModelIsEnabled
Missing XML docs.

2021-06-28 15:55 UTC, cozminvelciu commented on Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
> +        public string NewModelName
Missing XML docs.

2021-06-28 15:55 UTC, cozminvelciu commented on Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
> +                            this.ModeOpenOrOverwrite = true;
`ModeOpenOrOverwrite` is true on all switch branches. Why do we need it?

2021-06-28 15:55 UTC, cozminvelciu commented on Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
> +                            this.ModeCreate = mode == SupportedOperationModes.Create;
This can be taken out of the switch.

2021-06-28 15:55 UTC, cozminvelciu commented on Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
> +                            this.SourceModelIsEnabled = true;
This could be taken out of the switch with code like: `this.SourceModelIsEnalbed = mode != SupportedOperationModes.Open`.

2021-06-28 15:55 UTC, cozminvelciu commented on Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
> +        private void SetProperties()
Missing XML docs.

2021-06-28 15:55 UTC, cozminvelciu commented on Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
> +            this.NewModelName = "StressTester_TemporaryTestModel";
Don't use hardcoded value here, use const from configuration.

2021-06-28 15:55 UTC, cozminvelciu commented on Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
> +                ElementShortName = this.ElementShortName.Trim().Replace(" ", "_"),
Is there any way to deny spaces in the field directly?

2021-06-28 15:55 UTC, cozminvelciu commented on Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
> +            await this.stressGenerator.GenerateTestObjects();
Why do we need these two calls (`GenerateTestObjects` and `CleanUpTestObjects`)?

2021-06-28 15:55 UTC, cozminvelciu commented on Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
> +        private void BindSourceEngineeringModels()
This function could be unified with `BindEngineeringModels` by passing it a criteria predicate / boolean flag to enable or disable filtering by model prefix.

2021-06-28 15:55 UTC, cozminvelciu commented on Modules/StressGenerator/Utils/StressGenerator.cs
> +            await session.Refresh();
Why are we no longer closing the session at the end?

2021-06-28 15:55 UTC, cozminvelciu commented on Modules/StressGenerator/Utils/StressGenerator.cs
> +            if (this.configuration.TestModelSetup == null)
I don't think we can ever reach this point with `TestModelSetup` being `null`. I would remove this check.

2021-06-28 15:55 UTC, cozminvelciu commented on Modules/StressGenerator/Utils/StressGenerator.cs
> +                    $"{configuration.ElementName}#{number:D3}",
I would leave the spaces before the element number in the name and shortname.

2021-06-28 15:55 UTC, cozminvelciu commented on Modules/StressGenerator/Utils/StressGenerator.cs
> +            if (valueSetClone == null)
I don't think we can ever reach this point with `valueSetClone` being `null`. I would remove this check.

2021-06-29 09:34 UTC, adrianchivu commented on Modules/StressGenerator/Utils/EngineeringModelSetupGenerator.cs
> +            if (sourceEngineeringModelSetup == null)
Yes. Tested with both servers and this code works.

2021-06-29 11:37 UTC, adrianchivu commented on Modules/StressGenerator/ViewModels/StressGeneratorConfiguration.cs
> +            this.TestObjectsNumber = 5;
Ok

2021-06-29 11:57 UTC, adrianchivu commented on Modules/StressGenerator/ViewModels/StressGeneratorConfiguration.cs
> +                    this.testObjectsNumber = MinNumberOfTestObjects;
User will not receive feedback, but you will not be able to start

2021-06-29 11:59 UTC, adrianchivu commented on Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
> +        private ObservableAsPropertyHelper<bool> canStress;
Because of this line: ```canExecuteStress.ToProperty(this, vm => vm.CanStress, out this.canStress);```

2021-06-29 12:15 UTC, adrianchivu commented on Modules/StressGenerator/Utils/StressGenerator.cs
> +                    $"{configuration.ElementName}#{number:D3}",
Ok

2021-06-29 12:35 UTC, adrianchivu commented on Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
> +            await this.stressGenerator.GenerateTestObjects();
The current flow is: Init(), Create(), Cleanup()

2021-06-29 12:46 UTC, adrianchivu commented on Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
> +                            this.ModeOpenOrOverwrite = true;
Removed, the logic is keept using modeCreate only flag.

2021-06-29 12:54 UTC, adrianchivu commented on Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
> +                ElementShortName = this.ElementShortName.Trim().Replace(" ", "_"),
Probably regex on xaml file.

2021-06-30 06:21 UTC, cozminvelciu commented on Modules/StressGenerator/ViewModels/StressGeneratorConfiguration.cs
> +                    this.testObjectsNumber = MinNumberOfTestObjects;
I think we should add a little warning sign in the UI next to the invalid fields that prevent starting, as the user will have no idea what is wrong and what settings prevents them from using the tool.

2021-06-30 06:35 UTC, cozminvelciu commented on Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
> +    public sealed class StressGeneratorViewModel : BaseModuleViewModel
Shouldn't the sealed class be the base class `BaseModuleViewModel`?

2021-06-30 06:35 UTC, cozminvelciu commented on Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
>                      switch (mode)
Do we still need this `switch` as it only executes code on the `CreateOverwrite` branch? Would it be better to swap to an `if`?

2021-06-30 06:35 UTC, cozminvelciu commented on Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
> +            await this.stressGenerator.GenerateTestObjects();
My bad, I had the impression this was in a different function. It totally makes sense here, of course.

2021-06-30 07:11 UTC, cozminvelciu requested changes

2021-06-30 07:11 UTC, cozminvelciu commented on Modules/StressGenerator/Utils/EngineeringModelSetupGenerator.cs
>              return engineeringModelSetup;
Write should not return the EMS since it's the same that has been passed as an argument to the call.

2021-06-30 07:11 UTC, cozminvelciu commented on Modules/StressGenerator/Utils/GeneratorHelper.cs
> +﻿
Unneeded extra newline.

2021-06-30 07:11 UTC, cozminvelciu commented on Modules/StressGenerator/Utils/GeneratorHelper.cs
> +    internal static class GeneratorHelper
Missing XML docs.

2021-06-30 07:11 UTC, cozminvelciu commented on Modules/StressGenerator/Utils/GeneratorHelper.cs
> +    internal static class GeneratorHelper
`GeneratorHelper` is not a suggestive enough name. I would [currently] rename this to `WriteHelper`.

2021-06-30 07:30 UTC, adrianchivu commented on Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
> +    public sealed class StressGeneratorViewModel : BaseModuleViewModel
No.

2021-06-30 07:39 UTC, adrianchivu commented on Modules/StressGenerator/Utils/StressGenerator.cs
> -            await session.Refresh();
A LoginLogoutEvent is sent in this case.

2021-06-30 15:02 UTC, cozminvelciu commented on Modules/StressGenerator/ViewModels/StressGeneratorConfiguration.cs
> +                    this.testObjectsNumber = MinNumberOfTestObjects;
Will be solved as part of an upcoming UI improvements issue.

2021-06-30 20:30 UTC, cozminvelciu approved these changes

2021-06-30 20:32 UTC, merged